model:
    name: 'vae'
    num_classes: 6

training:
    num_epochs: 10
    learning_rate: 0.003
    batch_size: 64

data:
    data_dir: './Data/'
    annos_file: './annotations_classif.json'
    image_size: 68

optimizer:
    name: 'ADAM'
    params:
        lr: 0.01
        weight_decay: 0.001
        
scheduler:
    name: 'StepLR'
    params:
    step_size: 10
    gamma: 0.1
